package com.elsasa.bgud.util

import java.math.BigInteger
import java.security.SecureRandom

/**
 * ULID generation for device-owned technical identity (Return Order
 * Architecture IR-RO-01, S4.4).
 *
 * IR-RO-01 fixes the representation: `ReturnOrderId` is a 26-character
 * Crockford Base32 string generated by a Kotlin ULID implementation matching
 * the platform's `Ulid.NewUlid().ToString()` format (`Ulid` 1.2.6, used by
 * `btr.domain`/`btr.application`). No `UNIQUEIDENTIFIER`, no GUID, and no
 * GUID-to-ULID conversion is introduced.
 *
 * Canonical ULID layout: a 48-bit big-endian millisecond timestamp followed by
 * 80 bits of randomness, rendered as 26 Base32 digits over the 128-bit value.
 * Because 32^26 > 2^128, the most significant digit carries only 3 bits — this
 * is exactly the string the platform's `Ulid.NewUlid().ToString()` emits, so a
 * device-generated id is indistinguishable in shape from an office-generated
 * one.
 */
object Ulid {

    /** Crockford Base32 alphabet: no I, L, O or U. */
    private const val ENCODING = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"

    private const val ULID_CHARS = 26
    private const val GROUP_MASK = 0x1F

    private val random = SecureRandom()

    /** Canonical ULID string for the current instant. */
    fun newUlid(): String = newUlid(System.currentTimeMillis())

    /**
     * Canonical ULID string for [timestampMillis].
     *
     * Exposed for inspection/testing; production callers use [newUlid].
     */
    fun newUlid(timestampMillis: Long): String {
        val bytes = ByteArray(16)
        bytes[0] = ((timestampMillis ushr 40) and 0xFF).toByte()
        bytes[1] = ((timestampMillis ushr 32) and 0xFF).toByte()
        bytes[2] = ((timestampMillis ushr 24) and 0xFF).toByte()
        bytes[3] = ((timestampMillis ushr 16) and 0xFF).toByte()
        bytes[4] = ((timestampMillis ushr 8) and 0xFF).toByte()
        bytes[5] = (timestampMillis and 0xFF).toByte()
        val entropy = ByteArray(10)
        random.nextBytes(entropy)
        entropy.copyInto(bytes, 6)
        return encode(bytes)
    }

    /**
     * Renders a 16-byte ULID (6-byte timestamp + 10-byte randomness) as 26
     * Crockford Base32 digits — the canonical `Ulid.ToString()` encoding.
     */
    fun encode(bytes: ByteArray): String {
        require(bytes.size == 16) { "ULID requires exactly 16 bytes" }
        val value = BigInteger(1, bytes)
        val mask = BigInteger.valueOf(GROUP_MASK.toLong())
        val sb = StringBuilder(ULID_CHARS)
        for (i in 0 until ULID_CHARS) {
            val shift = 5 * (ULID_CHARS - 1 - i)
            sb.append(ENCODING[value.shiftRight(shift).and(mask).toInt()])
        }
        return sb.toString()
    }
}
