<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>btr.portal.worker.admin</RootNamespace>
    <AssemblyName>btr.portal.worker.admin</AssemblyName>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ResolveAssemblyReferencesSilent>true</ResolveAssemblyReferencesSilent>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>

</Project>
