CREATE TABLE [dbo].[BTRADE_User]
(
    UserId   VARCHAR(50) NOT NULL CONSTRAINT DF_BTRADE_User_UserId   DEFAULT(''),
    UserName VARCHAR(50) NOT NULL CONSTRAINT DF_BTRADE_User_UserName DEFAULT(''),
    Password VARCHAR(64) NOT NULL CONSTRAINT DF_BTRADE_User_Password DEFAULT(''),
    RoleId   VARCHAR(5)  NOT NULL CONSTRAINT DF_BTRADE_User_RoleId   DEFAULT(''),
    IsAktif  BIT         NOT NULL CONSTRAINT DF_BTRADE_User_IsAktif  DEFAULT(0),
    ServerId VARCHAR(5)  NOT NULL CONSTRAINT DF_BTRADE_User_ServerId DEFAULT(''),

    CONSTRAINT PK_BTRADE_User PRIMARY KEY CLUSTERED (UserId)
)
