IF NOT EXISTS (SELECT 1 FROM BTR_RoleMenu WHERE RoleId = 'SYSAD' AND MenuId = 'SM7')
	INSERT INTO BTR_RoleMenu (RoleId, MenuId) VALUES ('SYSAD', 'SM7');
GO

IF NOT EXISTS (SELECT 1 FROM BTR_RoleMenu WHERE RoleId = 'LEADR' AND MenuId = 'SM7')
	INSERT INTO BTR_RoleMenu (RoleId, MenuId) VALUES ('LEADR', 'SM7');
GO

IF NOT EXISTS (SELECT 1 FROM BTR_RoleMenu WHERE RoleId = 'SFKTR' AND MenuId = 'SM7')
	INSERT INTO BTR_RoleMenu (RoleId, MenuId) VALUES ('SFKTR', 'SM7');
GO
