IF NOT EXISTS (SELECT 1 FROM BTR_ParamSistem WHERE ParamCode = 'ROUTE_CYCLE_ANCHOR_DATE')
	INSERT INTO BTR_ParamSistem (ParamCode, ParamValue)
	VALUES ('ROUTE_CYCLE_ANCHOR_DATE', '2026-01-05');
GO

IF NOT EXISTS (SELECT 1 FROM BTR_ParamSistem WHERE ParamCode = 'VISIT_PLAN_HORIZON_DAYS')
	INSERT INTO BTR_ParamSistem (ParamCode, ParamValue)
	VALUES ('VISIT_PLAN_HORIZON_DAYS', '90');
GO
